M48
; DRILL file {KiCad 8.0.0} date 2024-07-21T16:15:32-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-07-21T16:15:32-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X194.385Y-93.3
X194.385Y-99.08
T2
X104.28Y-69.52
X104.28Y-130.48
X195.72Y-69.52
X195.72Y-130.48
M30
